/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user account */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login and receive a JWT access token */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current authenticated user info */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout current user (client-side token invalidation) */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update current user profile */
        patch: operations["AuthController_updateProfile"];
        trace?: never;
    };
    "/auth/addresses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all addresses for the current user */
        get: operations["AuthController_getAddresses"];
        put?: never;
        /** Add a new delivery address */
        post: operations["AuthController_addAddress"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/addresses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a delivery address */
        delete: operations["AuthController_deleteAddress"];
        options?: never;
        head?: never;
        /** Update an existing delivery address */
        patch: operations["AuthController_updateAddress"];
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all orders (customers see only their own) */
        get: operations["OrderController_findAll"];
        put?: never;
        /** Place a new order */
        post: operations["OrderController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single order by ID */
        get: operations["OrderController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update order status (Admin/Manager only) */
        patch: operations["OrderController_updateStatus"];
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all sneakers (supports filtering via query params) */
        get: operations["ProductsController_findAll"];
        put?: never;
        /** Create a new sneaker (Admin/Manager only) */
        post: operations["ProductsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single sneaker by ID */
        get: operations["ProductsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a sneaker (Admin/Manager only) */
        patch: operations["ProductsController_update"];
        trace?: never;
    };
    "/products/variants/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a sneaker variant (Admin/Manager only) */
        patch: operations["ProductsController_updateVariant"];
        trace?: never;
    };
    "/brands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all brands */
        get: operations["BrandController_findAll"];
        put?: never;
        /** Create a new brand (Admin/Manager only) */
        post: operations["BrandController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single brand by ID */
        get: operations["BrandController_findOne"];
        put?: never;
        post?: never;
        /** Delete a brand (Admin/Manager only) */
        delete: operations["BrandController_remove"];
        options?: never;
        head?: never;
        /** Update a brand (Admin/Manager only) */
        patch: operations["BrandController_update"];
        trace?: never;
    };
    "/favourites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all favourite sneakers for the current user */
        get: operations["FavouriteController_getFavourites"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/favourites/{sneakerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a sneaker to favourites */
        post: operations["FavouriteController_addToFavourite"];
        /** Remove a sneaker from favourites */
        delete: operations["FavouriteController_removeFromFavourite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current user's cart */
        get: operations["CartController_getCart"];
        put?: never;
        /** Add an item to the cart */
        post: operations["CartController_addToCart"];
        /** Clear the entire cart */
        delete: operations["CartController_clearCart"];
        options?: never;
        head?: never;
        /** Update quantity of a cart item */
        patch: operations["CartController_updateCartItem"];
        trace?: never;
    };
    "/cart/{variantId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a specific item from the cart */
        delete: operations["CartController_removeFromCart"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/order/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get payment info for a specific order */
        get: operations["PaymentController_getPayment"];
        put?: never;
        /** Process payment for an order */
        post: operations["PaymentController_processPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/order/{orderId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update payment status (Admin/Manager only) */
        patch: operations["PaymentController_updatePaymentStatus"];
        trace?: never;
    };
    "/media/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["MediaController_uploadFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MediaController_getMedia"];
        put?: never;
        post?: never;
        delete: operations["MediaController_deleteMedia"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chatbot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a message to the AI shopping chatbot */
        post: operations["ChatbotController_chat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            /**
             * @description User email address
             * @example nguyenvana@example.com
             */
            email: string;
            /**
             * @description User password (min 6 chars)
             * @example Password@123
             */
            password: string;
            /**
             * @description Full name
             * @example Nguyễn Văn A
             */
            name: string;
        };
        LoginDto: {
            /**
             * @description User email address
             * @example nguyenvana@example.com
             */
            email: string;
            /**
             * @description User password
             * @example Password@123
             */
            password: string;
        };
        UpdateProfileDto: {
            /**
             * @description Updated full name
             * @example Nguyễn Văn B
             */
            name?: string;
            /**
             * @description Updated phone number
             * @example 0987654321
             */
            phone?: string;
            /**
             * @description Media ID for avatar image
             * @example 10
             */
            avatarId?: number;
        };
        AddressDto: {
            /**
             * @description Street address
             * @example 123 Nguyễn Trãi
             */
            street: string;
            /**
             * @description City
             * @example Hà Nội
             */
            city: string;
            /**
             * @description District
             * @example Quận 1
             */
            district?: string;
            /**
             * @description Set as default address
             * @example true
             */
            isDefault?: boolean;
        };
        OrderItemDto: {
            /**
             * @description Variant ID
             * @example 3
             */
            variantId: number;
            /**
             * @description Quantity
             * @example 2
             */
            quantity: number;
        };
        CreateOrderDto: {
            /** @description List of items in the order */
            items: components["schemas"]["OrderItemDto"][];
            /**
             * @description Delivery address
             * @example 123 Nguyễn Trãi, Hà Nội
             */
            address: string;
            /**
             * @description Contact phone number
             * @example 0912345678
             */
            phone: string;
            /**
             * @description Payment method (COD, BANK_TRANSFER, etc.)
             * @example COD
             */
            paymentMethod: string;
            /**
             * @description Order note
             * @example Please leave at the door
             */
            note?: string;
        };
        UpdateOrderStatusDto: {
            /**
             * @description New order status (PENDING, CONFIRMED, SHIPPED, DELIVERED, CANCELLED)
             * @example CONFIRMED
             */
            status: string;
        };
        CreateSneakerDto: {
            /**
             * @description Sneaker name
             * @example Nike Air Max 90
             */
            name: string;
            /**
             * @description Sneaker description
             * @example Classic running shoe with visible Air cushioning
             */
            description: string;
            /**
             * @description Brand ID
             * @example 1
             */
            brandId: number;
            /**
             * @description Category ID
             * @example 2
             */
            categoryId: number;
        };
        UpdateSneakerDto: {
            /**
             * @description Updated sneaker name
             * @example Nike Air Max 95
             */
            name?: string;
            /**
             * @description Updated sneaker description
             * @example Updated description
             */
            description?: string;
            /**
             * @description Updated brand ID
             * @example 2
             */
            brandId?: number;
        };
        UpdateVariantDto: {
            /**
             * @description Variant color
             * @example Black
             */
            color?: string;
            /**
             * @description Shoe size (EU)
             * @example 42
             */
            size?: number;
            /**
             * @description Price in VND
             * @example 2500000
             */
            price?: number;
            /**
             * @description Stock quantity
             * @example 100
             */
            stock?: number;
        };
        CreateBrandDto: {
            /**
             * @description Brand name
             * @example Nike
             */
            name: string;
            /**
             * @description Brand description
             * @example American multinational footwear company
             */
            description?: string;
            /**
             * @description Media ID for brand logo
             * @example 5
             */
            logoId?: number;
            /**
             * @description Media ID for brand banner image
             * @example 6
             */
            imageId?: number;
        };
        UpdateBrandDto: {
            /**
             * @description Updated brand name
             * @example Adidas
             */
            name?: string;
            /**
             * @description Updated brand description
             * @example German multinational corporation
             */
            description?: string;
            /**
             * @description Media ID for updated brand logo
             * @example 7
             */
            logoId?: number;
            /**
             * @description Media ID for updated brand banner image
             * @example 8
             */
            imageId?: number;
        };
        CartItemDto: {
            /**
             * @description Variant ID to add to cart
             * @example 3
             */
            variantId: number;
            /**
             * @description Quantity (defaults to 1)
             * @example 2
             */
            quantity?: number;
        };
        UpdateCartItemDto: {
            /**
             * @description Variant ID of the item to update
             * @example 3
             */
            variantId: number;
            /**
             * @description New quantity (0 removes the item)
             * @example 5
             */
            quantity: number;
        };
        ProcessPaymentDto: {
            /**
             * @description Payment method (COD, BANK_TRANSFER, MOMO, etc.)
             * @example COD
             */
            method: string;
        };
        UpdatePaymentStatusDto: {
            /**
             * @description Payment status (PENDING, COMPLETED, FAILED, REFUNDED)
             * @example COMPLETED
             */
            status: string;
            /**
             * @description Transaction ID from payment provider
             * @example TXN-20240504-001
             */
            transactionId?: string;
        };
        ChatMessageDto: {
            /**
             * @description User message to the chatbot
             * @example Tôi muốn tìm giày Nike size 42
             */
            message: string;
            /**
             * @description Chat history for context
             * @example [
             *       {
             *         "role": "user",
             *         "parts": [
             *           {
             *             "text": "Hello"
             *           }
             *         ]
             *       }
             *     ]
             */
            history?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            /** @description User registered successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Login successful, returns access_token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileDto"];
            };
        };
        responses: {
            /** @description Profile updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_getAddresses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of addresses */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_addAddress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddressDto"];
            };
        };
        responses: {
            /** @description Address added successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_deleteAddress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Address deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_updateAddress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddressDto"];
            };
        };
        responses: {
            /** @description Address updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrderController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of orders */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrderController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderDto"];
            };
        };
        responses: {
            /** @description Order placed successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrderController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Order not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrderController_updateStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrderStatusDto"];
            };
        };
        responses: {
            /** @description Order status updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_findAll: {
        parameters: {
            query?: {
                /** @description Search by name */
                search?: string;
                /** @description Filter by category ID */
                categoryId?: number;
                /** @description Filter by brand ID */
                brandId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of sneakers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSneakerDto"];
            };
        };
        responses: {
            /** @description Sneaker created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden – insufficient role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sneaker details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sneaker not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSneakerDto"];
            };
        };
        responses: {
            /** @description Sneaker updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_updateVariant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateVariantDto"];
            };
        };
        responses: {
            /** @description Variant updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BrandController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of all brands */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BrandController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBrandDto"];
            };
        };
        responses: {
            /** @description Brand created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BrandController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Brand details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Brand not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BrandController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Brand deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BrandController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBrandDto"];
            };
        };
        responses: {
            /** @description Brand updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FavouriteController_getFavourites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of favourite sneakers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FavouriteController_addToFavourite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sneakerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sneaker added to favourites */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FavouriteController_removeFromFavourite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sneakerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sneaker removed from favourites */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CartController_getCart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cart contents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CartController_addToCart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CartItemDto"];
            };
        };
        responses: {
            /** @description Item added to cart */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CartController_clearCart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cart cleared */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CartController_updateCartItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCartItemDto"];
            };
        };
        responses: {
            /** @description Cart item updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CartController_removeFromCart: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                variantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Item removed from cart */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PaymentController_getPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Payment details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Payment not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PaymentController_processPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProcessPaymentDto"];
            };
        };
        responses: {
            /** @description Payment processed successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PaymentController_updatePaymentStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePaymentStatusDto"];
            };
        };
        responses: {
            /** @description Payment status updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MediaController_uploadFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MediaController_getMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MediaController_deleteMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChatbotController_chat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatMessageDto"];
            };
        };
        responses: {
            /** @description Chatbot reply with optional product recommendations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
